#!/usr/bin/env python3
"""Explicit party templates from the 15-round GDD and six authorized additional verbs."""
from pathlib import Path
import json
ROOT=Path(__file__).resolve().parents[2]
STD=['i','o','t','l','s','tripod','screw_left','screw_right']
ITEMS=['slow_time','bomb','helper_drop','preview_peek','junk_rain','fog','speed_up','spin_lock']
families=json.loads((ROOT/'assets/data/shapes/families.json').read_text())['families']
awkward=families['hollow']+families['party']
gifts=awkward+families['pento_3d']+['giant_slab']
rows=[]
def slots(board='grid',entry='top',clear='layer',collapse='slice',top='lose',goal='clear_race'):
 return dict(board_kind=board,spawn_entry=entry,clear_detector=clear,collapse=collapse,top_out_check=top,goal_evaluator=goal)
def versus(id,name,rule,goal,height=10,knobs=None,rules=None):
 level={'schema':1,'id':'versus_'+id,'biome':'meadow','tier':1,'name':'MODE_'+id.upper(),'board':{'width':6,'depth':6,'h_play':height},'pieces':{'shapes':STD},'knobs':{'fall.g0':1.0,'goal.top_out':'lose','goal.warnings_max':0},'goal':goal,'rules':rules or [],'stars':{}}
 level['knobs'].update(knobs or {})
 rows.append({'id':id,'mode':id,'category':'versus','tags':['versus'],'name':name,'card_name':name,'name_key':'MODE_'+id.upper(),'rule':rule,'rule_key':'ROUND_'+id.upper()+'_RULE','icon':id,'duration_ms':240000,'weight':1.0,'standing_metric':'alive_time' if id=='survival' else 'race_progress','standing_tiebreak':'score','interaction_hook':['item'],'item_whitelist':ITEMS,'items_enabled':True,'item_trigger':'clear','skill_support':True,'perk_support':True,'twist_limit':2,'piece_pool':STD,'board':level['board'],'slots':slots(goal='last_standing' if id=='survival' else goal['type'],clear='none' if id in ['build_race','shape_race'] else 'layer',top='trim' if id in ['build_race','shape_race'] else 'lose'),'level':level,'params':{},'always_available':True,'source':'design/gdd/mode-minigame-randomizer.md#core-rules'})
versus('clear_race','Clear Race','Be first to clear two layers.',{'type':'clear_n','n':2})
versus('build_race','Build Race','Build to the line while clears are off.',{'type':'height','h_target':10},12,{'goal.top_out':'trim','clear.detector':'none'},[{'id':'build_race','params':{'topout_rule':'trim'}}])
versus('shape_race','Shape Race','Fill the same two-layer target before your rivals.',{'type':'shape','target_shape':{'layers':{'0':['++++++']*6,'1':['++++++']*6}}},8,{'goal.top_out':'trim','clear.detector':'none'},[{'id':'fill_shape','params':{'topout_rule':'trim'}}])
versus('survival','Survival','Keep building; the last player standing wins.',{'type':'endless'},10,{'fall.ramp_per_min':0.15,'fall.g_max':6.0})
def mg(n,name,card,rule,seconds,metric,hook,slot,board,params,controls,pool=None,items=None,trigger='none',tie='score'):
 id=f'mg{n:02d}'
 rows.append({'id':id,'minigame_id':f'MG{n}','mode':id,'category':'minigame','tags':['minigame'],'name':name,'card_name':card,'name_key':f'MG_{n:02d}_NAME','rule':rule,'rule_key':f'MG_{n:02d}_RULE','icon':id,'duration_ms':seconds*1000,'weight':1.0,'standing_metric':metric,'standing_tiebreak':tie,'interaction_hook':hook,'slots':slot,'board':dict(width=board[0],depth=board[1],h_play=board[2]),'piece_pool':pool or STD,'items_enabled':bool(items),'item_whitelist':items or [],'item_trigger':trigger,'twist_limit':0,'skill_support':False,'perk_support':False,'controls':controls,'params':{'k_cb':0.5,'leader_send_scale':0.5,'attack_warn_ms':1000,'pick_window_ms':1500,'ghost_send_ms':15000,**params},'always_available':True,'source':'design/gdd/tournament-minigames.md' if n<=15 else 'docs/design/additional-party-minigames.md' if n<=21 else 'design/gdd/party-minigames-wave2.md'})
 if n>=22: rows[-1]['rules_script']='res://src/game/minigames/rules_c.gd' if n<=29 else 'res://src/game/minigames/rules_d.gd'
mg(1,'Hole in the Wall','Wall Fit','Rotate your block so its silhouette fits the approaching hole.',90,'score',['send'],slots(entry='frame',clear='none',collapse='none',top='none',goal='score_timer'),(4,4,4),{'wall_start_ms':6000,'wall_min_ms':3000,'hole_slack_start':2,'hole_slack_end':0,'tight_charge':3,'tight_advance_ms':1000,'stun_ms':1000},['rotate','send'])
mg(2,'Copycat','Copy Cat','Remember the model, then rebuild it with the same blocks.',150,'score',['send'],slots(clear='none',top='trim',goal='score_timer'),(4,4,4),{'show_ms':5000,'show_min_ms':2000,'smudge_ms':1500,'model_pieces_min':2,'model_pieces_max':4,'model_cubes_min':6,'model_cubes_max':14,'speed_bonus':50,'speed_window_ms':30000},['move','rotate','hard_drop','send'],['duo','tri_straight','tri_corner','i','o','tripod'])
mg(3,'Colour Rush','Colour Rush','Pop matching flavours; chains send grey garbage to rivals.',90,'score',['send'],slots(clear='colour_connect',collapse='cascade',top='trim',goal='score_timer'),(5,5,12),{'colour_count':4,'grey_chain_min':2,'grey_warn_locks':1},['move','rotate','hard_drop','send'])
mg(4,'Perfect Stack','Perfect Stack','Release each sliding block and keep every cube supported.',60,'height',['steal'],slots(entry='slide_in',clear='none',collapse='stack_trim',top='trim',goal='height_timer'),(4,4,24),{'slide_gates':'alternate','slide_start_speed':2.0,'slide_end_speed':4.0,'perfect_charge':3,'slab_width':4,'slab_depth':4,'shield_hits':1},['release','send'])
mg(5,'Crane Tower','Crane Tower','Release swinging blocks and hold your tower above the line.',120,'race_progress',['send'],slots(board='physics',entry='crane',clear='none',collapse='physics',top='drops',goal='height_race'),(6,6,16),{'swing_period_ms':2400,'height_target':8,'hold_above_ms':3000,'drops_allowed':3,'height_ribbon':2,'gust_speed_scale':1.3,'gust_ms':8000},['rotate','release','send'])
mg(6,'Mascot Bridge Race','Bridge Race','Build a walkway that takes your mascot to the far flag.',150,'race_progress',['send'],slots(clear='none',top='trim',goal='path'),(8,3,8),{'gap_cells':6,'step_height_max':1,'bird_charge_ms':25000,'attack_warn_ms':1500,'bird_protect_mascot':True},['move','rotate','hard_drop','send'])
mg(7,'Box Packers','Box Packers','Fill every cell in your box and send awkward blocks.',120,'race_progress',['send'],slots(clear='none',top='trim',goal='fill_race'),(4,4,3),{'box_cells':48,'hold_enabled':True,'awkward_pool':awkward,'queue_front':True},['move','rotate','hard_drop','hold','send'])
mg(8,'Gift Exchange','Gift Exchange','Clear four layers while choosing blocks to gift your rivals.',150,'race_progress',['send'],slots(goal='clear_race'),(5,5,10),{'clear_target':4,'gift_offer_count':2,'gift_delay_pieces':1,'gift_cap':2,'gift_pool':gifts,'tap_to_pick':True},['move','rotate','hard_drop','gift_choose','send'])
mg(9,'Speed Sort','Speed Sort','Swipe each block into its matching colour bin.',60,'score',['shared','steal'],slots(board='none',entry='chute',clear='none',collapse='none',top='none',goal='score_timer'),(3,1,1),{'colour_count':3,'golden_every_ms':10000,'golden_steal_points':3,'jam_ms':1000,'speed_ramp':True},['sort'])
mg(10,'Shadow Duel','Shadow Duel','Build a stack that matches both silhouettes exactly.',150,'score',['send'],slots(clear='none',top='trim',goal='puzzle_race'),(4,4,4),{'puzzles_target':3,'front_axis':'z','side_axis':'x','flicker_ms':3000},['move','rotate','hard_drop','send'])
mg(11,'Memory Tower','Memory Tower','Build from memory as your locked blocks fade from view.',120,'height',['item'],slots(clear='none',top='trim',goal='height_timer'),(5,5,6),{'visible_ms':2000,'height_ribbon':1},['move','rotate','hard_drop','use_item'],items=['fog','speed_up','spin_lock','slow_time','preview_peek'],trigger='height_ribbon')
mg(12,'Spin Cycle','Spin Cycle','Clear layers while your tower turns every three locks.',120,'score',['send','item'],slots(goal='score_timer'),(5,5,10),{'turn_locks':3,'turn_degrees':90,'extra_spin_min_layers':2,'attack_warn_ms':1000},['move','rotate','hard_drop','send','use_item'],items=ITEMS,trigger='clear')
mg(13,'Floor Is Lava','Lava Floor','Keep a half-full safe layer above the rising lava.',150,'alive_time',['send'],slots(clear='none',top='lose',goal='last_standing'),(4,4,24),{'lava_start_ms':12000,'lava_min_ms':7000,'lava_step_ms':500,'lava_cover':0.5,'unsafe_loss_ms':2000,'pump_charge':4,'pump_advance_ms':4000},['move','rotate','hard_drop','send'],tie='height')
mg(14,'Hot Block','Hot Block','Clear the smoking block to pass it before its fuse expires.',150,'race_progress',['shared'],slots(goal='clear_race'),(5,5,12),{'clear_target':5,'hot_shape':'big_cube','fuse_ms':20000,'blast_junk':2,'hot_instances':1},['move','rotate','hard_drop'])
mg(15,'Catch Tower','Catch Tower','Slide the tray under the falling blocks to grow your tower.',75,'height',['send'],slots(entry='sky_lanes',clear='none',collapse='stack_trim',top='trim',goal='height_timer'),(7,7,24),{'tray_width':3,'tray_depth':3,'sky_width':7,'sky_depth':7,'gravity_scale':3.0,'shadow_ms':1000,'slippery_charge':5,'slippery_ms':6000,'slippery_step':2},['tray_move','send'])
mg(16,'Rhythm Blocks','Rhythm Blocks','Hit the matching lane as each seeded block reaches the beat.',60,'score',['send'],slots(board='none',entry='rhythm',clear='none',collapse='none',top='none',goal='score_timer'),(4,1,1),{'bpm':120,'hit_window_ms':180,'lane_count':4,'offbeat_charge':8,'offbeat_ms':5000},['mg_rhythm_hit','send'])
mg(17,'Magnet Maze','Magnet Maze','Move and reverse polarity to pull every block into a dock.',90,'race_progress',['send'],slots(board='none',entry='magnet',clear='none',collapse='none',top='none',goal='dock_race'),(4,4,1),{'maze_width':4,'maze_depth':4,'reversal_ms':5000,'connected_path':True},['mg_magnet_move','mg_polarity','mg_reset','send'])
mg(18,'Balloon Volley','Balloon Volley','Return the block in its flight window to score against rivals.',75,'score',['send'],slots(board='none',entry='volley',clear='none',collapse='none',top='none',goal='score_timer'),(1,1,1),{'return_window_ms':400,'flight_ms':2400,'attack_warn_ms':1000},['mg_volley','send'])
mg(19,'Gem Grab','Gem Grab','Collect gems on the block island and deposit your bag.',90,'score',['send','shared'],slots(board='none',entry='island',clear='none',collapse='none',top='none',goal='score_timer'),(7,7,2),{'gem_count':6,'bag_capacity':5,'golden_every_ms':10000,'sticky_ms':5000},['mg_move','mg_deposit','send'])
mg(20,'Paint Dash','Paint Dash','Walk the block island and paint the exposed stencil faces.',90,'score',['send'],slots(board='none',entry='paint',clear='none',collapse='none',top='none',goal='score_timer'),(7,7,3),{'stencil_faces':12,'wet_faces':2,'wet_ms':5000},['mg_move','mg_paint','send'])
mg(21,'Balance Budget','Balance Budget','Choose and place blocks so both pans balance to earn a rack.',90,'score',['send'],slots(board='none',entry='balance',clear='none',collapse='none',top='none',goal='score_timer'),(4,4,8),{'offer_count':3,'rack_limit':8,'weight_surprise':2,'balanced_goal':3},['mg_choose','mg_pan','mg_release','send'])
# Wave 2 (design/gdd/party-minigames-wave2.md). Board-less rounds keep a 1x1x1 nominal board.
def mg2(n,name,rule,seconds,metric,hook,entry,board,params,controls,goal='score_timer',tie='score'):
 mg(n,name,name,rule,seconds,metric,hook,slots(board='none' if board==(1,1,1) else 'grid',entry=entry,clear='none',collapse='none',top='none',goal=goal),board,params,controls,tie=tie)
mg2(22,'Block Bowling','Aim, add spin and roll your block to knock down the cube pins.',90,'score',['send'],'bowling',(5,9,1),{'roll_step_ms':120,'curve_row':4,'balls_per_frame':2,'strike_points':20,'spare_points':15,'greased_charge':2,'greased_ms':8000},['mg_aim','mg_spin','mg_bowl','send'])
mg2(23,'Simon Stack','Watch the pads light up, then repeat the whole sequence.',90,'score',['send'],'sequence',(1,1,1),{'start_len':3,'flash_ms':600,'gap_ms':200,'scramble_charge':2},['mg_pad','send'])
mg2(24,'Quick Drop','Tap the instant the block turns green, but never before.',60,'score',['shared'],'signal',(1,1,1),{'wait_min_ms':1500,'wait_max_ms':4500,'timeout_ms':1500,'gap_ms':1200,'fake_chance':0.3,'false_start_penalty':2,'shared_bonus':3},['mg_tap'])
mg2(25,'Cube Count','Count every cube in the tower before it disappears.',75,'score',['send'],'count',(4,4,8),{'show_ms':3000,'show_min_ms':1200,'peek_cut_ms':1200,'fast_ms':2000,'correct_points':3,'fast_bonus':2,'peek_charge':2},['mg_answer','send'])
mg2(26,'Odd Block Out','Spot the one block that is a mirror twin, not a turn.',75,'score',['send'],'odd',(1,1,1),{'copies':4,'copies_late':5,'late_after':4,'pick_lock_ms':1000,'decoy_charge':3,'decoy_copies':6},['mg_pick','send'])
mg2(27,'Toy Pairs','Flip two cards at a time and match every pair of blocks.',90,'score',['send'],'pairs',(1,1,1),{'grid_w':4,'grid_h':4,'mismatch_ms':800,'match_points':2,'clear_bonus':5,'shuffle_charge':3},['mg_flip','send'])
mg2(28,'Block Dodge','Step between lanes to dodge the falling blocks.',90,'alive_time',['send'],'dodge',(5,1,1),{'lanes':5,'hearts':3,'shadow_ms':900,'rain_start_ms':1100,'rain_min_ms':450,'rain_step_ms':40,'wide_after_ms':30000,'survive_point_ms':10000,'rain_charge':3,'extra_rain':3},['mg_step','send'],goal='last_standing',tie='score')
mg2(29,'Slide Shuffle','Slide the tiles back into the picture of the block.',120,'race_progress',['send'],'slide',(3,3,1),{'scramble_moves':30,'puzzles_target':2,'nudge_charge':5,'nudge_moves':3},['mg_slide','send'],goal='puzzle_race')
mg2(30,'Mirror Mirror','Paint the mirror image of the pattern on the other side.',90,'score',['send'],'mirror',(5,5,1),{'start_cells':6,'max_cells':12,'flip_charge':2,'flip_accuracy':0.9},['mg_move','mg_paint','mg_submit','send'])
mg2(31,'Colour Count','Count the blocks of the target colour in the parade.',75,'score',['send'],'tally',(1,1,1),{'parade_min':12,'parade_max':20,'parade_ms':450,'parade_min_ms':250,'fast_cut_ms':150,'correct_points':3,'fast_charge':2},['mg_answer','send'])
mg2(32,'Whack-a-Block','Tap the blocks as they pop up, but leave the bombs alone.',60,'score',['send'],'whack',(3,3,1),{'pop_ms':900,'pop_min_ms':550,'golden_chance':0.1,'bomb_chance':0.125,'block_points':1,'golden_points':3,'bomb_penalty':2,'decoy_charge':8,'decoy_count':4,'disguise_ms':300},['mg_whack','send'])
mg2(33,'Tower Pull','Pull bars from your tower without letting it topple.',120,'score',['send'],'pull',(3,3,12),{'layers':9,'rebuild_ms':2500,'topple_penalty':5,'deep_bonus_layers':3,'wobble_charge':4,'wobble_ms':5000},['mg_pull','send'])
mg2(34,'Spin Match','Turn your block to match the target in as few turns as you can.',90,'score',['send'],'spin',(1,1,1),{'par_bonus':6,'sticky_charge':3,'sticky_ms':8000},['mg_rotate','mg_submit','send'])
mg2(35,'Plinko Drop','Drop your block through the pegs into the best bucket.',75,'score',['shared'],'plinko',(7,6,1),{'columns':7,'rows':6,'buckets':[1,3,5,10,5,3,1],'drop_step_ms':180,'drop_cooldown_ms':1200,'jackpot_ms':15000,'jackpot_window_ms':4000,'jackpot_bonus':5},['mg_aim','mg_bowl'])
mg2(36,'Treasure Dig','Dig the patch and follow the hot-cold numbers to the buried block.',120,'score',['send'],'dig',(6,6,1),{'patch':6,'max_reward':12,'min_reward':2,'mud_charge':2,'mud_count':3},['mg_move','mg_dig','send'])
out=ROOT/'assets/data/tournament';out.mkdir(parents=True,exist_ok=True)
(out/'templates.json').write_text(json.dumps({'schema':1,'source':['design/gdd/mode-minigame-randomizer.md','design/gdd/tournament-minigames.md','docs/design/additional-party-minigames.md'],'templates':rows},indent=2)+'\n')
(out/'randomizer.json').write_text(json.dumps({'schema':1,'minigame_share':0.4,'mg_no_repeat_rounds':3,'rerolls_per_player':1,'show_ms':3000,'reroll_window_ms':5000,'twists_round1':0,'twists_round2':1,'twists_round4':2},indent=2)+'\n')
cfg=json.loads((ROOT/'assets/data/meta/modes.json').read_text());cfg['tournament']['modes']=[r['id'] for r in rows];(ROOT/'assets/data/meta/modes.json').write_text(json.dumps(cfg,indent=2)+'\n')
print('Explicit templates',len(rows),'minigames',sum(r['category']=='minigame' for r in rows))
