extends SceneTree
const UI = preload("res://src/ui/game_ui.gd")
var seen=[]
func _initialize(): call_deferred("_run")
func press(ui,label):
    for b in ui._root.find_children("*","Button",true,false):
      if b.text==label and b.is_visible_in_tree():
        b.pressed.emit()
        return
    assert(false,"Button missing: "+label)
func _run():
    var ui=UI.new()
    root.add_child(ui)
    await process_frame
    ui.intent.connect(func(id,args):seen.append({"id":id,"args":args}))
    ui.show_title({"has_profile":true})
    press(ui,"Continue  →")
    assert(seen[-1].id==&"continue")
    ui.show_profiles({"profiles":[]})
    press(ui,"＋  New profile")
    assert(ui.current_screen=="profile_form")
    press(ui,"Save friend  ✓")
    assert(seen[-1].id==&"create_profile" and seen[-1].args.name=="Clover")
    assert(ui.handle_back())
    assert(ui.current_screen=="profiles")
    ui.show_profiles({"profiles":[null,null,{"name":"Juniper"},null],"active_slot":2})
    press(ui,"Juniper  ✓")
    assert(seen[-1].id==&"select_profile" and seen[-1].args.slot==2)
    ui.show_settings({"prefs":{"reduced_motion":"system"}})
    for option in ui._root.find_children("*","OptionButton",true,false):
      if option.get_item_text(0)=="Follow system":
        assert(option.selected==0)
        option.item_selected.emit(2)
        assert(seen[-1].id==&"set_pref" and seen[-1].args.key=="reduced_motion" and seen[-1].args.value=="on")
    ui.show_hud({"can_tilt":true,"can_roll":true,"skill_ready":true,"skill_charge":1000,"selected_potion":"slow_time","potion_count":2,"held_shape":"corner"})
    ui.update_hud({"wobble":{}})
    assert(not ui._hud_labels.rules.text.contains("Wobble"))
    press(ui,"DROP ↓")
    assert(seen[-1].id==&"drop")
    press(ui,"Roll ›")
    assert(seen[-1].id==&"rotate" and seen[-1].args.axis==&"roll")
    press(ui,"Hold")
    assert(seen[-1].id==&"hold")
    press(ui,"Skill ✓")
    assert(seen[-1].id==&"use_skill")
    press(ui,"Potion 2")
    assert(seen[-1].id==&"use_item")
    ui.show_hud({"capabilities":{"kit":true,"undo":true,"reset":true,"choose_down":true,"ice_flick":true,"flicks_left":1}})
    press(ui,"Kit")
    assert(seen[-1].id==&"open_tools")
    ui.show_tools({"capabilities":{"kit":true,"undo":true,"reset":true,"choose_down":true,"ice_flick":true,"flicks_left":1},"kit_choices":[{"shape_id":"mono","remaining":2},{"shape_id":"duo","remaining":0}],"selection_remaining":2,"allowed_down":[Vector3i(0,-1,0)],"allowed_flick":[Vector3i(0,0,-1)]})
    press(ui,"Mono  ×2")
    assert(seen[-1].id==&"pick_shape" and seen[-1].args.shape_id=="mono")
    press(ui,"↓  Down")
    assert(seen[-1].id==&"choose_down" and seen[-1].args.direction==Vector3i(0,-1,0))
    press(ui,"↑  Away")
    assert(seen[-1].id==&"flick" and seen[-1].args.direction==Vector3i(0,0,-1))
    press(ui,"Undo last turn  ↶")
    assert(seen[-1].id==&"undo")
    press(ui,"Reset this puzzle  ↻")
    assert(seen[-1].id==&"reset")
    ui.show_story({"story_key":"meadow_01","phase":"post","beats":[{"left":"cloud","right":"pip","emote_left":"sparkle","emote_right":"heart","symbol":"basket","pose_left":"wave","pose_right":"give","duration":.15}]})
    assert(ui.current_screen=="story")
    await create_timer(.2).timeout
    assert(seen[-1].id==&"story_done" and seen[-1].args.story_key=="meadow_01")
    ui.show_story({"story_key":"meadow_02","phase":"post","beats":[{"duration":1}]})
    press(ui,"→")
    assert(seen[-1].id==&"story_done" and seen[-1].args.story_key=="meadow_02")
    ui.show_story({"story_key":"intro","phase":"pre","beats":[{"duration":.15}]})
    assert(ui.handle_back() and ui.current_screen=="story")
    await create_timer(.2).timeout
    assert(seen[-1].id==&"story_done" and seen[-1].args.phase=="pre")
    ui.show_pause()
    press(ui,"Restart…")
    assert(ui.current_screen=="confirm")
    assert(ui.handle_back())
    assert(ui.current_screen=="pause")
    ui.show_tournament({"profile_name":"Clover"})
    for picker in ui._root.find_children("*","OptionButton",true,false):
      if picker.get_item_text(0)=="Cloud Wizard": picker.select(3)
    press(ui,"Host party")
    assert(seen[-1].id==&"host_lan" and seen[-1].args.port==24680 and seen[-1].args.character=="c4")
    press(ui,"Start practice  →")
    assert(seen[-1].id==&"start_tournament" and seen[-1].args.players.size()==2 and seen[-1].args.players[0].character_id=="c4")
    ui.show_physics()
    for picker in ui._root.find_children("*","OptionButton",true,false):
      if picker.get_item_text(0)=="Tower Race":
        picker.select(11)
        picker.item_selected.emit(11)
    press(ui,"Open the toy box  →")
    assert(seen[-1].id==&"start_physics" and seen[-1].args.variant=="domino_chain")
    ui.show_shop({"wallet":5,"items":[{"id":"slow_time","name":"Slow time","price":3}]})
    press(ui,"Buy  ·  ★ 3")
    assert(ui.current_screen=="confirm")
    press(ui,"Yes, continue  ✓")
    assert(seen[-1].id==&"buy_item" and seen[-1].args.item_id=="slow_time")
    assert(not seen.any(func(row):return row.id==&"noop"))
    print("UI_INTENT_FLOW_PASS: profiles/null slots, settings enum, HUD, gameplay/kit/direction/undo/reset, wordless story completion/skip, restart, LAN, bot practice, shop; no noop emitted")
    ui.queue_free()
    await process_frame
    quit(0)
