## Exports the wave-2 party landmark toys (MG22-MG36) built by WtMinigameArt to GLB,
## and writes assets/models/party_wave2/manifest.json with triangle counts, sizes
## and SHA-256 per file. The geometry is original primitive meshes; nothing external.
## Usage: godot --headless --path . -s res://tools/art/export_party_wave2_models.gd
extends SceneTree

const Art := preload("res://src/view/wt_minigame_art.gd")
const OUT_DIR: String = "res://assets/models/party_wave2/"
const FIRST: int = 22
const LAST: int = 36
const MAX_BYTES: int = 400 * 1024


func _initialize() -> void:
	DirAccess.make_dir_recursive_absolute(ProjectSettings.globalize_path(OUT_DIR))
	var entries: Array[Dictionary] = []
	var failures: int = 0
	for n: int in range(FIRST, LAST + 1):
		var id: String = "mg%02d" % n
		var theme: Dictionary = Art.THEMES[id]
		var toy: Node3D = Art.create(id)
		toy.name = "party_%s_%s" % [id, theme.prop]
		root.add_child(toy)
		var stats: Dictionary = _mesh_stats(toy)
		var file: String = "party_%s_%s.glb" % [id, theme.prop]
		var path: String = OUT_DIR + file
		var doc := GLTFDocument.new()
		var state := GLTFState.new()
		var err: Error = doc.append_from_scene(toy, state)
		if err == OK:
			err = doc.write_to_filesystem(state, path)
		root.remove_child(toy)
		toy.free()
		var bytes: int = FileAccess.get_file_as_bytes(path).size() if err == OK else 0
		if err != OK or bytes == 0 or bytes > MAX_BYTES:
			failures += 1
			push_error("%s: export err=%d bytes=%d" % [path, err, bytes])
		entries.append({
			"id": id,
			"name": theme.name,
			"prop": theme.prop,
			"file": "assets/models/party_wave2/" + file,
			"triangles": stats.triangles,
			"mesh_objects": stats.meshes,
			"bytes": bytes,
			"sha256": FileAccess.get_sha256(path),
			"factory": "res://src/view/wt_minigame_art.gd::create(%s)" % id,
			"provenance": "original primitive geometry generated by WtMinigameArt",
		})
		print("PARTY_WAVE2_EXPORT %s tris=%d meshes=%d bytes=%d err=%d" % [path, stats.triangles, stats.meshes, bytes, err])
	var manifest: Dictionary = {
		"schema": 1,
		"generator": "res://tools/art/export_party_wave2_models.gd",
		"godot_version": Engine.get_version_info().string,
		"units": "metres; base plate radius 1.7, plate top at Y=0, Y-up",
		"collision": "decorative landmark toys only; gameplay owns all rules and collision",
		"license": "MIT (repository LICENSE); original primitive geometry and flat matte materials; no external assets or textures",
		"assets": entries,
	}
	var out := FileAccess.open(OUT_DIR + "manifest.json", FileAccess.WRITE)
	out.store_string(JSON.stringify(manifest, "  ") + "\n")
	out.close()
	print("PARTY_WAVE2_EXPORT done count=%d failures=%d" % [entries.size(), failures])
	quit(1 if failures > 0 else 0)


func _mesh_stats(node: Node) -> Dictionary:
	var triangles: int = 0
	var meshes: int = 0
	for child: Node in node.find_children("*", "MeshInstance3D", true, false):
		var mesh: Mesh = (child as MeshInstance3D).mesh
		if mesh == null:
			continue
		meshes += 1
		triangles += mesh.get_faces().size() / 3
	return {"triangles": triangles, "meshes": meshes}
